FROM python:3.6

RUN apt-get update && apt-get install -y --no-install-recommends \ 
            vim python-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /home
COPY *.py ./
COPY run.sh ./
RUN chmod +x run.sh

CMD ./run.sh